---
title: "R Notebook"
output: html_notebook
---



```{r}
library(maps)
library(plotly)
library(colorspace)
library(tidyverse)
library(ggplot2)
library(ggiraph)
```
```{r}
states <- map_data("state")

head(states)

states <- map_data("state")
tn<-subset(states, region %in% c("tennessee"))
tn_df<-subset(states, region=="tennessee")
counties<-map_data("county")
tn_county<-subset(counties, region=="tennessee")
tn_base <- ggplot(data = tn_df, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")
tn_base +  
  geom_polygon(data = tn_county, fill = NA, color = "white") +
  geom_polygon(color = "black", fill = NA)
```


```{r}
simpleCap <- function(x) {
  sapply(x, function(x){
    x <- tolower(x)
    s <- strsplit(x, " ")[[1]]
    paste(toupper(substring(s, 1,1)), substring(s, 2),
        sep="", collapse=" ")
  }
  )
}


tn_county_rename <- tn_county %>%
  rename(county = subregion) %>%
  mutate(county = simpleCap(county))


  

```

```{r}
acs_data_tn <- read.csv("data/demographics/acs_full_data.csv")

head(acs_data_tn)
```


```{r}
acs_data_tn_cpop <- acs_data_tn %>%
  group_by(year,county) %>%
  summarise(sum(pop)) %>%
  rename(
    countypop = `sum(pop)`)



acs_data_tn <- 
  inner_join(acs_data_tn,acs_data_tn_cpop,by = c("county","year"), copy = FALSE)



```


```{r}
popcalc <- ((acs_data_tn$pop/acs_data_tn$countypop) * 100)
    

acs_data_tn <- acs_data_tn %>%
  mutate(
    percap = case_when(
      race == "asian" ~ popcalc,
      race == "black" ~ popcalc,
      race == "first nation" ~ popcalc,
      race == "native hawaiian or pacific islander" ~ popcalc,
      race == "other race" ~ popcalc,
      race == "white" ~ popcalc
    ))

acs_data_tn_np <- acs_data_tn

```


```{r}

acs_data_tn <- acs_data_tn %>%
  pivot_wider(
    names_from = race,
    values_from = percap
  ) %>%
  select(year,county,countypop,asian,black,`first nation`,`native hawaiian or pacific islander`,`other race`,white)%>%
  replace(is.na(.),0) %>%
  group_by(year,county,countypop)%>%
  summarise_each(funs(sum))




```



```{r}
acs_data_tn <- acs_data_tn %>% 
    mutate(county = simpleCap(county))


acs_data_tn %>%
  filter(county =="Mcminn")

tn_county_rename %>%
  filter(county == "Mcminn")


acs_data_tn <- 
  inner_join(acs_data_tn,tn_county_rename,by = "county", copy = FALSE)


View(acs_data_tn)



```


```{r}

write.csv(acs_data_tn,"data/demographics/acs_data_tn_geo.csv",row.names = FALSE)
```

```{r}


acs_data_tn %>%
  filter(county =="Mcminn")

```




```{r}
ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank())
```


```{r}

acs_data_tn %>%
  filter(county =="Mcminn")

acs_data_tn_test <- acs_data_tn %>%
  filter(year == 2000)

acs_data_tn_test %>%
  filter(county == "Mcminn")


```


```{r}
elb<-tn_base + 
      geom_polygon(data = acs_data_tn_test, aes(fill = white, text = sprintf('County: %s\nWhite: %s\nBlack: %s\nAsian: %s\nNative Hawaiian or Pacific Islander: %s\nFirst Nation: %s\nOther Race: %s'
                                                                             , county, round(white, 2),round(black,2),round(asian,2),
                                                                             round(`first nation`,2),round(`native hawaiian or pacific islander`,2),
                                                                             round(`other race`,2))), color = "black") +
      geom_polygon(color = "black", fill = NA) +
    theme_bw() +
      ditch_the_axes
```



```{r}
elb<-elb +
            scale_fill_gradientn(colours = colorspace::diverging_hcl(3,palette = "Blue-Red"),breaks = c(0, 25, 50, 75)) 

```


```{r}

ggplotly(elb,tooltip = "text")

```
```{r}
acs_data_tn_np %>%
  filter(county=="Knox")%>%
  ggplot(aes(x=year,y=percap,color=race,group=race))+
  geom_line(size=1.25)

write.csv(acs_data_tn_np,"data/demographics/acs_data_tn_np.csv",row.names = FALSE)

```



```{r}
acs_data_tn_np %>%
  filter(county=="Davidson")%>%
  ggplot(aes(x=year,y=percap,group=race,color=race))+
  geom_line()
```

